### ISSUE TITLE
USB Resoursce Busy error and fix

### ISSUE THREAD

**Issue by i-hayes** [weewx/weewx-wmr200#1]
I believe I have fixed this error. I have uploaded a patch file of the changes.

[wmr200.txt](https://github.com/weewx/weewx-wmr200/files/5993645/wmr200.txt)

Before the changes the driver was crashing about every 1.5 days. It has now been over 11 days and no problems.

From reading the error logs from other users I think this will fix this for all OS's and python versions.

The error was with this driver and how it was handling the opening of the USB port. For some reason this driver was structured differently to the other weather station drivers.

Cheers
Ian

**Comment by tkeffer** [comment]
Thanks for taking a look at this!

Trying to understand exactly what you did. I see two changes:

1. The `find_device()` function is now static, and returns the device rather than setting an attribute in class `UsbDevice`.
2. Added the ability to search for an explicit `device_id`. However, the code does not actually use that ability.

Am I missing anything else?

If those are the only two changes, could you outline to me how these changes would affect the driver? They just seem like code refactoring. Perhaps I'm missing something, but I don't see how it would change anything as far as the device is concerned.

**Comment by i-hayes** [comment]
The important change is moving **find_device()** from startup to within **open_device()**.

**_find_dev()** or **find_device()** will effectively do the same thing so long as either is called from within **open_device()**.

I opted for a local variable (dev) to ensure it was recreated every time.

Looking at the error logs by various users in the forum the error appeared to be the OS's were reassigning the USB ports at various times after bootup. This meant the weather console would disappear from the drivers identified location, my change means this no longer happens as the console is detected everytime the USB port is opened.

cheers
Ian

**Comment by tkeffer** [comment]
Ah, I missed that!

Excellent work. Thanks so much for solving this elusive error!
